# Generated by Django 4.2.8 on 2023-12-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_profile_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send',
            field=models.TextField(default=2, verbose_name='Рассылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Направление'),
        ),
    ]
